---
- hosts: all
  roles:
    - base
    - hackspaceusers
  vars_files:
    - vars/users.yml

- hosts: alvin
  roles:
    - doorbot
  tags:
    - doorbot

- hosts: acidburn
  roles:
    - mosquitto-server
    - telegram-bot

- hosts: wordpress.bikeshed.hacman.org.uk
  roles:
    - wordpress

- hosts: all
  roles:
    - { role: vm, when: vm is defined }

- hosts: bikeshed.hacman.org.uk
  roles:
    - vmhost
  vars_files:
    - vars/users.yml
