---
- hosts: all
  roles:
    - hackspaceusers

- hosts: alvin
  roles:
    - doorbot
  tags:
    - doorbot

- hosts: acidburn
  roles:
    - mosquitto-server
    - telegram-bot

- hosts: bikeshed.hacman.org.uk
  roles:
    - vmhost
