---
- include_vars:
    file: users.yml

- name: "Install packages"
  apt:
    name: "{{item}}"
    state: installed
    update_cache: yes
  with_items:
    - qemu-kvm
    - libvirt-clients
    - libvirt-daemon-system

- name: "Add users to libvirt groups"
  user:
    name: "{{item.username}}"
    groups: libvirt,kvm
    append: yes
  with_items: "{{users}}"

- name: "Grab some install media"
  get_url:
    url: "{{item}}"
    dest: /var/lib/libvirt/images/
  with_items:
    - https://cdimage.debian.org/debian-cd/current/multi-arch/iso-cd/debian-9.3.0-amd64-i386-netinst.iso
    - https://cdimage.debian.org/cdimage/openstack/current-9/debian-9-openstack-amd64.qcow2
