---

- name: Make sure hostname matches inventory_hostname
  hostname:
    name: "{{inventory_hostname}}"

- name: add hostname to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: '127.0.1.1	{{inventory_hostname}}	{{inventory_hostname_short}}'
    state: present

- name: Allow passwordless sudo for sudo users
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo  ALL=(ALL:ALL) NOPASSWD: ALL'
    validate: visudo -cf %s

- name: Install packages
  apt:
    name: "{{item}}"
    state: latest
    update_cache: true
  with_items:
    - vim
    - unattended-upgrades
