---
- name: "Add users"
  include: adduser.yml user="{{item}}"
  with_items: "{{users}}"

- name: Remove default users if they exist
  include: killuser.yml user="{{item}}"
  with_items:
    - pi
    - debian
    - fedora
